using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ChordGeneratorMAUI.DataAccess
{
    public static class ChordDatabase
    {
        public static List<string> Chords = new List<string>
        {
            "A",
            "B",
            "C",
            "D",
            "E",
            "F",
            "G",
            "A♭",
            "B♭",
            "C♭",
            "D♭",
            "E♭",
            "F♭",
            "G♭",
            "A#",
            "B#",
            "C#",
            "D#",
            "E#",
            "F#",
            "G#",
            "Amin",
            "Bmin",
            "Cmin",
            "Dmin",
            "Emin",
            "Fmin",
            "Gmin",
            "A♭min",
            "B♭min",
            "C♭min",
            "D♭min",
            "E♭min",
            "F♭min",
            "G♭min",
            "A#min",
            "B#min",
            "C#min",
            "D#min",
            "E#min",
            "F#min",
            "G#min",
            "A7",
            "B7",
            "C7",
            "D7",
            "E7",
            "F7",
            "G7",
            "A♭7",
            "B♭7",
            "C♭7",
            "D♭7",
            "E♭7",
            "F♭7",
            "G♭7",
            "A#7",
            "B#7",
            "C#7",
            "D#7",
            "E#7",
            "F#7",
            "G#7",
            "A -7",
            "B -7",
            "C -7",
            "D -7",
            "E -7",
            "F -7",
            "G -7",
            "A♭-7",
            "B♭-7",
            "C♭-7",
            "D♭-7",
            "E♭-7",
            "F♭-7",
            "G♭-7",
            "A# -7",
            "B# -7",
            "C# -7",
            "D# -7",
            "E# -7",
            "F# -7",
            "G# -7",
            "Amaj7",
            "Bmaj7",
            "Cmaj7",
            "Dmaj7",
            "Emaj7",
            "Fmaj7",
            "Gmaj7",
            "A♭maj7",
            "B♭maj7",
            "C♭maj7",
            "D♭maj7",
            "E♭maj7",
            "F♭maj7",
            "G♭maj7",
            "A#maj7",
            "B#maj7",
            "C#maj7",
            "D#maj7",
            "E#maj7",
            "F#maj7",
            "G#maj7",

            // 6th Chords
            "A6",
            "B6",
            "C6",
            "D6",
            "E6",
            "F6",
            "G6",
            "A♭6",
            "B♭6",
            "C♭6",
            "D♭6",
            "E♭6",
            "F♭6",
            "G♭6",
            "A#6",
            "B#6",
            "C#6",
            "D#6",
            "E#6",
            "F#6",
            "G#6",

            // Dominant 9th Chords
            "A9",
            "B9",
            "C9",
            "D9",
            "E9",
            "F9",
            "G9",
            "A♭9",
            "B♭9",
            "C♭9",
            "D♭9",
            "E♭9",
            "F♭9",
            "G♭9",
            "A#9",
            "B#9",
            "C#9",
            "D#9",
            "E#9",
            "F#9",
            "G#9",
        };
    }
}
